
CONSOLE_ENABLE = no
VIA_ENABLE = no
LTO_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
OLED_ENABLE = no
BACKLIGHT_ENABLE = no
ENCODER_ENABLE = no

TRI_LAYER_ENABLE = yes

MOUSEKEY_ENABLE = no # Mouse keys
EXTRAKEY_ENABLE = yes # Audio control and System controls
SPLIT_KEYBOARD = yes

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = no
UNICODEMAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
SEND_STRING_ENABLE = yes
