name: Build my QMK configuration

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: sofle
          keymap: tantalid
          local-keymap-path: keyboards/sofle/keymaps/tantalid

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-output
